CREATE TABLE game (
	game_id INTEGER	NOT NULL AUTO_INCREMENT,
	game_name VARCHAR(20) NOT NULL,
	game_shoe JSON,
	PRIMARY KEY (game_id)
	);

CREATE TABLE player (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL,
	points INTEGER NOT NULL,
	cards JSON,
	PRIMARY KEY (name)
	);